version: '2'
services:

  database:
    container_name: tech_challenge_db
    build:
      context: database
      dockerfile: Dockerfile
    image: tech_challenge_db:latest
    ports:
      - 3306:3306
    networks:
      - app_network

networks:
  app_network:
    driver: bridge