version: '2'
services:

  database:
    container_name: tech_challenge_db
    build:
      context: database
      dockerfile: Dockerfile
    image: tech_challenge_db:latest
    ports:
      - 3306:3306
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  followup-application:
    container_name: followup-application
    build:
      context: .
      dockerfile: Dockerfile
    image: followup-application:latest
    depends_on:
      - redis
      - database
    ports:
      - 8080:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge