name: Followup App CI with Maven

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
env:
  BRANCH_NAME: ${{github.ref_name}}
  APP_NAME: tech-challenge-fiap-followup

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout    
      uses: actions/checkout@v3

    - name: Branch Name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Create Docker Tag
      run: |
        if [[ ${{env.BRANCH_NAME}} == 'main' ]]
        then
          DOCKER_TAG="latest-${{ github.sha }}"
        else
          DOCKER_TAG="${{env.BRANCH_NAME}}-latest-${{ github.sha }}"
        fi
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    - name: Docker Tag
      run: echo ${{ env.DOCKER_TAG }}