name: Followup App CI with Maven

on:
  push:
    branches: [ "main" ]

env:
  BRANCH_NAME: ${{github.ref_name}}
  APP_NAME: tech-challenge-fiap-followup

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout    
      uses: actions/checkout@v3

    - name: Check Branch Name
      run: echo ${{ env.BRANCH_NAME }}

    - name: Create Docker Tag
      run: |
        if [[ ${{env.BRANCH_NAME}} == 'main' ]]
        then
          DOCKER_TAG="latest-${{ github.sha }}"
        else
          DOCKER_TAG="${{env.BRANCH_NAME}}-latest-${{ github.sha }}"
        fi
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

    - name: Check Docker Tag
      run: echo ${{ env.DOCKER_TAG }}

    - name: Docker Build
      run: docker build --tag ${{ env.APP_NAME }}:${{ env.DOCKER_TAG}} .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push to Amazon ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        image: ${{ env.APP_NAME }}:${{ env.DOCKER_TAG}}